import { Settings } from "../Settings";

const languageDataBase = {};

const init = ()=>{
	parseLocalization();
}
const parseLocalization = ()=>{
	LOCALIZATION_DATA.forEach(data => {
		const id = data.textId;
		const keys = Object.keys(data);
		keys.forEach( language => {
			if(language != 'textId'){
				if(!languageDataBase[id]) languageDataBase[id] = {};
				languageDataBase[id][language] = data[language];
			}
		})
	})
}

export const localize = id =>{
	let text = '?';
	if(languageDataBase[id]){
		text = languageDataBase[id][Settings.currentCountry];
		if(!text) text = languageDataBase[id]['us']
	}
	return text;
}

export const countries = ['us','de','jp','pt','fr','es','it','nl','ru','cz','jr'];

const LOCALIZATION_DATA = [
    {
        "textId": "mainmenu_singleplayer",
        "us": "Single Player",
        "nl": "Een Speler",
        "de": "Einzelspieler",
        "es": "Un solo jugador",
        "pt": "Um jogador",
        "cz": "Jeden hráč",
        "fr": "Joueur solo",
        "it": "Giocatore singolo",
        "jr": "Lon'ly Adventure",
        "jp": "シングルプレーヤー\r\n",
        "ru": "Одиночная игра"
    },
    {
        "textId": "mainmenu_multiplayer",
        "us": "Multiplayer",
        "nl": "Meerdere Spelers",
        "de": "Multiplayer",
        "es": "Multijugador",
        "pt": "Multiplayer",
        "cz": "Multiplayer",
        "fr": "Multijoueur",
        "it": "Multiplayer",
        "jr": "Play in a crew",
        "jp": "マルチプレイヤー\r",
        "ru": "Мультиплеер"
    },
    {
        "textId": "mainmenu_creategame",
        "us": "Create Game",
        "nl": "Maak Game",
        "de": "Spiel erstellen",
        "es": "Crear juego",
        "pt": "Criar jogo",
        "cz": "Vytvořit hru",
        "fr": "Créer un jeu",
        "it": "Crea gioco",
        "jr": "Start Crew",
        "jp": "クリエイトゲームズ",
        "ru": "Создать игровую"
    },
    {
        "textId": "mainmenu_changelevel",
        "us": "Change",
        "nl": "Verander",
        "de": "Ändern",
        "es": "Cambio",
        "pt": "Mudar",
        "cz": "Změna",
        "fr": "Changer",
        "it": "Modificare",
        "jp": "変更レベル",
        "ru": "Изменить"
    },
    {
        "textId": "mainmenu_selectlevel",
        "us": "Select Level",
        "nl": "Selecteer Level",
        "de": "Stufe auswählen",
        "es": "Selecciona el nivel",
        "pt": "Selecione o nível",
        "cz": "Vyberte úroveň",
        "fr": "Choisir le niveau",
        "it": "Seleziona livello",
        "jr": "Pick an island",
        "jp": "レベルを選択する",
        "ru": "Выберите уровень"
    },
    {
        "textId": "mainmenu_players",
        "us": "Players",
        "nl": "Spelers",
        "de": "Spieler",
        "es": "Jugadores",
        "pt": "Jogadoras",
        "cz": "Hráči",
        "fr": "Joueurs",
        "it": "Giocatori",
        "jr": "Mates",
        "jp": "選手紹介",
        "ru": "Игроки"
    },
    {
        "textId": "mainmenu_nolevel",
        "us": "Admin is selecting level",
        "nl": "Admin is level aan het uitzoeken",
        "de": "Admin wählt die Ebene aus",
        "es": "El administrador está seleccionando el nivel",
        "pt": "Admin está selecionando o nível",
        "cz": "Admin vybírá úroveň",
        "fr": "L'administrateur sélectionne le niveau",
        "it": "L'amministratore sta selezionando il livello",
        "jr": "Captain's steerin' the ship",
        "jp": "管理者がレベルを選択中",
        "ru": "Админ выбирает уровень"
    },
    {
        "textId": "mainmenu_ready",
        "us": "Ready",
        "nl": "Gereed",
        "de": "Bereit",
        "es": "Listo",
        "pt": "Preparar",
        "cz": "Připraven",
        "fr": "Prêt",
        "it": "Pronto",
        "jp": "レディ",
        "ru": "Готово"
    },
    {
        "textId": "mainmenu_start",
        "us": "Start",
        "nl": "Start",
        "de": "Start",
        "es": "Comienzo",
        "pt": "Começar",
        "cz": "Start",
        "fr": "Démarrer",
        "it": "Inizio",
        "jp": "スタート",
        "ru": "Начать"
    },
    {
        "textId": "mainmenu_admin",
        "us": "Admin",
        "nl": "Admin",
        "de": "Administrator",
        "es": "Administración",
        "pt": "Admin",
        "cz": "Admin",
        "fr": "Administrer",
        "it": "Amministratore",
        "jr": "Captain",
        "jp": "管理者",
        "ru": "Администратор"
    },
    {
        "textId": "mainmenu_connecting",
        "us": "Connecting",
        "nl": "Verbinden",
        "de": "Verbinden",
        "es": "Conexión",
        "pt": "Conectando",
        "cz": "Spojovací",
        "fr": "De liaison",
        "it": "Connessione",
        "jr": "Boardin' ship",
        "jp": "コネクティング",
        "ru": "Соединение"
    },
    {
        "textId": "mainmenu_waiting",
        "us": "Waiting",
        "nl": "Wachten",
        "de": "Warten",
        "es": "Esperando",
        "pt": "Esperando",
        "cz": "Čekání",
        "fr": "Attendre",
        "it": "In attesa",
        "jr": "Waitin'",
        "jp": "待機中",
        "ru": "В ожидании"
    },
    {
        "textId": "mainmenu_kick",
        "us": "Kick",
        "nl": "Trap",
        "de": "Trete",
        "es": "Patear",
        "pt": "Pontapé",
        "cz": "Kop",
        "fr": "Donner un coup",
        "it": "Calcio",
        "jr": "Throw overboard",
        "jp": "キックアウトする",
        "ru": "Выгнать"
    },
    {
        "textId": "mainmenu_leave",
        "us": "Leave",
        "nl": "Verlaat",
        "de": "Verlassen",
        "es": "Abandonar",
        "pt": "Deixar",
        "cz": "Odejít",
        "fr": "Quitter",
        "it": "Lasciare",
        "jr": "Avast!",
        "jp": "去る",
        "ru": "Покинуть игру"
    },
    {
        "textId": "mainmenu_quickplay",
        "us": "Quick Play",
        "nl": "Snel Spelen",
        "de": "Schnelles Spiel",
        "es": "Juego rápido",
        "pt": "Jogo rápido",
        "cz": "Rychlá hra",
        "fr": "Jeu rapide",
        "it": "Partita veloce",
        "jr": "Free sailin'",
        "jp": "クイックプレイ",
        "ru": "Быстрая игра"
    },
    {
        "textId": "mainmenu_createlevels",
        "us": "Create levels!",
        "nl": "Creëer levels!",
        "de": "Level erstellen!",
        "es": "¡Crea niveles!",
        "pt": "Crie níveis!",
        "cz": "Vytvoř level!",
        "fr": "Créer des niveaux!",
        "it": "Crea livelli!",
        "jr": "Build an island base",
        "jp": "レベル作成",
        "ru": "Создайте уровни!"
    },
    {
        "textId": "mainmenu_signup",
        "us": "Sign Up!",
        "nl": "Inschrijven!",
        "de": "Registrieren!",
        "es": "¡Inscribirse!",
        "pt": "Inscrever-se!",
        "cz": "Zaregistrovat se!",
        "fr": "S'inscrire!",
        "it": "Iscriviti!",
        "jp": "アカウント作成",
        "ru": "Войти в Учет. запись"
    },
    {
        "textId": "mainmenu_characters",
        "us": "Characters",
        "nl": "Karakters",
        "de": "Charaktere",
        "es": "Caracteres",
        "pt": "Personagens",
        "cz": "Postavy",
        "fr": "Personnages",
        "it": "Caratteri",
        "jr": "Buccaneers",
        "jp": "キャラクター",
        "ru": "Персонажи"
    },
    {
        "textId": "mainmenu_onlyfeatured",
        "us": "Only Featured",
        "nl": "Alleen Aanbevolen",
        "de": "Nur Empfohlene",
        "es": "Solo presentado",
        "pt": "Apenas em destaque",
        "cz": "Pouze doporučené",
        "fr": "Seulement en vedette",
        "it": "Solo in primo piano",
        "jr": "Only Mapped",
        "jp": "特別なレベルのみ",
        "ru": "Только избранные"
    },
    {
        "textId": "mainmenu_sorted",
        "us": "Sorted By:",
        "nl": "Gesorteerd Op:",
        "de": "Sortiert nach:",
        "es": "Ordenado por:",
        "pt": "Classificado por:",
        "cz": "Seřazeno podle",
        "fr": "Trié par:",
        "it": "Ordinato per:",
        "jr": "Marked as",
        "jp": "ソート順",
        "ru": "Отсортировано по:"
    },
    {
        "textId": "mainmenu_filters",
        "us": "Filters",
        "nl": "Filters",
        "de": "Filter",
        "es": "Filtros",
        "pt": "Filtros",
        "cz": "Filtr",
        "fr": "Filtres",
        "it": "Filtri",
        "jp": "フィルター類",
        "ru": "Фильтры"
    },
    {
        "textId": "mainmenu_allvehicles",
        "us": "All Vehicles",
        "nl": "Alle Voertuigen",
        "de": "Alle Fahrzeuge",
        "es": "Todos los vehiculos",
        "pt": "Todos os veículos",
        "cz": "Všechna vozidla",
        "fr": "Tous les véhicules",
        "it": "Tutti i veicoli",
        "jr": "All ships",
        "jp": "諸車",
        "ru": "Tранспортные средства"
    },
    {
        "textId": "mainmenu_best_rated",
        "us": "Best Rated",
        "nl": "Best Beoordeeld",
        "de": "Beste Bewertung",
        "es": "Mejor Puntuado",
        "pt": "Melhor avaliado",
        "cz": "Nejlépe hodnocené",
        "fr": "Mieux noté",
        "it": "I più votati",
        "jr": "Most Bootyful",
        "jp": "最高品質",
        "ru": "Лучший рейтинг"
    },
    {
        "textId": "mainmenu_most_played",
        "us": "Most Played",
        "nl": "Meest Gespeeld",
        "de": "Meistgespielt",
        "es": "Mas Jugado",
        "pt": "Mais Jogadas",
        "cz": "Nejhranější ",
        "fr": "Les plus joués",
        "it": "Più giocato",
        "jr": "Most Plundered",
        "jp": "一番人気",
        "ru": "Наипопулярнейший"
    },
    {
        "textId": "mainmenu_newest",
        "us": "Newest",
        "nl": "Nieuwste",
        "de": "Neuste",
        "es": "Mas Nuevo",
        "pt": "Mais novo",
        "cz": "Nejnovější",
        "fr": "Plus récents",
        "it": "Più nuovo",
        "jr": "Newly Discovered",
        "jp": "最新",
        "ru": "Новейший"
    },
    {
        "textId": "mainmenu_oldest",
        "us": "Oldest",
        "nl": "Oudste",
        "de": "Älteste",
        "es": "Mas Viejo",
        "pt": "Mais velho",
        "cz": "Nejstarší",
        "fr": "Plus anciens",
        "it": "Più vecchio",
        "jr": "Ol' sea legends",
        "jp": "最古の",
        "ru": "Старейший"
    },
    {
        "textId": "mainmenu_editor",
        "us": "Editor",
        "nl": "Editor",
        "de": "Editor",
        "es": "Editor",
        "pt": "Editor",
        "cz": "Editor",
        "fr": "Éditeur",
        "it": "Editor",
        "jr": "Sea Buildin'",
        "jp": "エディター",
        "ru": "редактор"
    },
    {
        "textId": "mainmenu_by",
        "us": "By",
        "nl": "Door",
        "de": "Von",
        "es": "De",
        "pt": "De",
        "cz": "Od",
        "fr": "Par",
        "it": "Da",
        "jr": "Aye",
        "jp": "執筆者",
        "ru": "автор"
    },
    {
        "textId": "mainmenu_login",
        "us": "login",
        "nl": "inloggen",
        "de": "einloggen",
        "es": "Entrar",
        "pt": "Entrar",
        "cz": "Přihlásit se",
        "fr": "Se connecter",
        "it": "Entra",
        "jr": "Set Sail",
        "jp": "サインイン",
        "ru": "Авторизация"
    },
    {
        "textId": "mainmenu_today",
        "us": "Today",
        "nl": "Vandaag",
        "de": "Heute",
        "es": "Hoy",
        "pt": "Hoje",
        "cz": "Dnes",
        "fr": "Aujourd'hui",
        "it": "Oggi",
        "jr": "Since this day",
        "jp": "今日",
        "ru": "Сегодня"
    },
    {
        "textId": "mainmenu_thisweek",
        "us": "This Week",
        "nl": "Deze Week",
        "de": "Diese Woche",
        "es": "Esta Semana",
        "pt": "Esta semana",
        "cz": "Tento týden",
        "fr": "Cette semaine",
        "it": "Questa settimana",
        "jr": "Since 7 nights ago",
        "jp": "今週は",
        "ru": "За эту неделю"
    },
    {
        "textId": "mainmenu_thismonth",
        "us": "This Month",
        "nl": "Deze Maand",
        "de": "Diesen Monat",
        "es": "Este Mes",
        "pt": "Este mês",
        "cz": "Tento měsíc",
        "fr": "Ce mois",
        "it": "Questo mese",
        "jr": "Since 1 moon ago",
        "jp": "今月は",
        "ru": "За этот месяц"
    },
    {
        "textId": "mainmenu_anytime",
        "us": "All Time",
        "nl": "Altijd",
        "de": "Jederzeit",
        "es": "Siempre",
        "pt": "Sempre",
        "cz": "Kdykoli",
        "fr": "N'importe quand",
        "it": "Per sempre",
        "jr": "Since forever!",
        "jp": "オールタイム",
        "ru": "За все время"
    },
    {
        "textId": "mainmenu_more",
        "us": "More",
        "nl": "Meer",
        "de": "Mehr",
        "es": "Mas",
        "pt": "Mais",
        "cz": "Více",
        "fr": "Plus",
        "it": "Di più",
        "jr": "Moarrgh",
        "jp": "もっと見る",
        "ru": "Более"
    },
    {
        "textId": "mainmenu_availablepc",
        "us": "Available on PC",
        "nl": "Beschikbaar op PC",
        "de": "Auf PC Verfügbar",
        "es": "Disponible en PC",
        "pt": "Disponível no PC",
        "cz": "K dispozici na PC",
        "fr": "Disponible sur PC",
        "it": "Disponibile su PC",
        "jr": "Available on Pirate Crew",
        "jp": "PCのみ",
        "ru": "Доступно на ПК"
    },
    {
        "textId": "settings_settings",
        "us": "Settings",
        "nl": "Instellingen",
        "de": "Einstellungen",
        "es": "Ajustes",
        "pt": "Definições",
        "cz": "Nastavení",
        "fr": "Paramètres",
        "it": "Impostazioni",
        "jr": "Mess with yer boat",
        "jp": "設定",
        "ru": "Настройки"
    },
    {
        "textId": "settings_on",
        "us": "on",
        "nl": "aan",
        "de": "ein",
        "es": "Encendido ",
        "pt": "Ligado",
        "cz": "Zapnout",
        "fr": "Activé",
        "it": "Attivato",
        "jr": "Aye",
        "jp": "於",
        "ru": "Вкл."
    },
    {
        "textId": "settings_off",
        "us": "off",
        "nl": "uit",
        "de": "aus",
        "es": "Apagado",
        "pt": "Desligado",
        "cz": "Vypnout",
        "fr": "Désactivé",
        "it": "Spento",
        "jr": "Nay",
        "jp": "オフ",
        "ru": "Выкл."
    },
    {
        "textId": "settings_music",
        "us": "Music",
        "nl": "Muziek",
        "de": "Musik",
        "es": "Música",
        "pt": "Música",
        "cz": "Hudba",
        "fr": "Musique",
        "it": "Musica",
        "jr": "Shanties",
        "jp": "音楽",
        "ru": "Музыка"
    },
    {
        "textId": "settings_blood",
        "us": "Blood",
        "nl": "Bloed",
        "de": "Blut",
        "es": "Sangre",
        "pt": "Sangue",
        "cz": "Krev",
        "fr": "Sang",
        "it": "Sangue",
        "jr": "Juice",
        "jp": "血",
        "ru": "Кровь"
    },
    {
        "textId": "settings_gore",
        "us": "Gore",
        "nl": "Wonden",
        "de": "Zwickel",
        "es": "Cornear",
        "pt": "Escornar",
        "cz": "Úrazy",
        "fr": "Gore",
        "it": "Incornare",
        "jr": "Meat",
        "jp": "臓物",
        "ru": "Насилие"
    },
    {
        "textId": "settings_fullscreen",
        "us": "Fullscreen",
        "nl": "Volledig scherm",
        "de": "Vollbild",
        "es": "Pantalla completa",
        "pt": "Tela completa",
        "cz": "Celá obrazovka",
        "fr": "Plein écran",
        "it": "Schermo intero",
        "jr": "Take of yer eyepatch",
        "jp": "最大画面",
        "ru": "Полноэкранный"
    },
    {
        "textId": "settings_consent",
        "us": "Cookies",
        "jr": "Crackers",
        "jp": "クッキー",
        "ru": "Печенье"
    },
    {
        "textId": "settings_credits",
        "us": "Credits",
        "nl": "Credits",
        "de": "Beiträge",
        "es": "Créditos",
        "pt": "Créditos",
        "cz": "Autoři",
        "fr": "Crédits",
        "it": "Crediti",
        "jr": "Crewmates",
        "jp": "てんすう",
        "ru": "Авторы"
    },
    {
        "textId": "settings_installedmod",
        "us": "Mod active",
        "nl": "Mod actief",
        "de": "Aktive Mod",
        "es": "Mod activo",
        "pt": "Mod ativo",
        "cz": "Aktivní mod",
        "fr": "Mod actif",
        "it": "Mod attivo",
        "jr": "New Seas?",
        "jp": "アクティブMOD",
        "ru": "Активные моды"
    },
    {
        "textId": "settings_installmod",
        "us": "Modify",
        "nl": "Modificeer",
        "de": "Modifizieren",
        "es": "Modificar",
        "pt": "Modificar",
        "cz": "Modifikovat",
        "fr": "Modifier",
        "it": "Modificare",
        "jr": "Decorate yer ship",
        "jp": "MODを追加する",
        "ru": "Моды"
    },
    {
        "textId": "settings_none",
        "us": "None",
        "nl": "Geen",
        "de": "Keine",
        "es": "Ninguna",
        "pt": "Nenhum",
        "cz": "Žádný",
        "fr": "Rien",
        "it": "Nessuno",
        "jr": "Nay",
        "jp": "何もない",
        "ru": "Нет"
    },
    {
        "textId": "characterselect_select_character",
        "us": "Select a character",
        "nl": "Kies een character",
        "de": "Wähle einen Charakter",
        "es": "Seleccionar Personaje",
        "pt": "Selecione o personagem",
        "cz": "Vybrat postavu",
        "fr": "Sélectionnez un personnage",
        "it": "Seleziona personaggio",
        "jr": "Pick yer captain",
        "jp": "キャラクターを選択する",
        "ru": "Выберите персонажа"
    },
    {
        "textId": "vehicleselect_select_vehicle",
        "us": "Select a vehicle",
        "nl": "Kies een voertuig",
        "de": "Wähle ein Fahrzeug",
        "es": "Elige un vehículo",
        "pt": "Selecione o veículo",
        "cz": "Vybrat vozidlo",
        "fr": "Sélectionner un véhicule",
        "it": "Scegli un veicolo",
        "jr": "Pick yer boat",
        "jp": "車両を選択する",
        "ru": "Выберите транспортное средство"
    },
    {
        "textId": "levelbanner_share",
        "us": "Share",
        "nl": "Delen",
        "de": "Teilen",
        "es": "Compartir",
        "pt": "Compartilhar",
        "cz": "Sdílet",
        "fr": "Partager",
        "it": "Condividere",
        "jr": "Share with yer maties",
        "jp": "分け合う",
        "ru": "Поделитесь"
    },
    {
        "textId": "levelbanner_favorite",
        "us": "Favorite",
        "nl": "Favoriet",
        "de": "Favorit",
        "es": "Favorito",
        "pt": "Favorito",
        "cz": "Oblíbené",
        "fr": "Préféré",
        "it": "Preferito",
        "jr": "Treasure",
        "jp": "お気に入り登録",
        "ru": "сделать избранным"
    },
    {
        "textId": "levelbanner_gameplays",
        "us": "Gameplays",
        "nl": "Gespeeld",
        "de": "Gespielt",
        "es": "Jugadas",
        "pt": "Jogadas",
        "cz": "Hry",
        "fr": "Joué",
        "it": "Gioca",
        "jr": "Voyages",
        "jp": "再生回数",
        "ru": "Геймплей"
    },
    {
        "textId": "levelbanner_votes",
        "us": "Votes",
        "nl": "Stemmen",
        "de": "Bewertungen",
        "es": "Votos",
        "pt": "Votos",
        "cz": "Hlasování",
        "fr": "Votes",
        "it": "Voti",
        "jr": "Ayes",
        "jp": "投票スコア",
        "ru": "Голоса"
    },
    {
        "textId": "levelbanner_viewall",
        "us": "View All",
        "nl": "Zie Alles",
        "de": "Alle Ansehen",
        "es": "Ver Todos",
        "pt": "Ver todos",
        "cz": "Zobrazit vše",
        "fr": "Voir tous",
        "it": "Vedi tutto",
        "jr": "All landlubbers",
        "jp": "すべてのエントリーを表示",
        "ru": "Посмотреть все"
    },
    {
        "textId": "levelbanner_play",
        "us": "Play",
        "nl": "Spelen",
        "de": "Spielen",
        "es": "Jugar",
        "pt": "Jogar",
        "cz": "Hrát",
        "fr": "Jouer",
        "it": "Giocare",
        "jr": "Start the raid!",
        "jp": "プレイ",
        "ru": "Играть"
    },
    {
        "textId": "levelbanner_back",
        "us": "Back",
        "nl": "Terug",
        "de": "Zurück",
        "es": "Regresar",
        "pt": "Voltar",
        "cz": "Zpět",
        "fr": "Fermer",
        "it": "Ritornare",
        "jr": "Avast!",
        "jp": "戻る",
        "ru": "Назад"
    },
    {
        "textId": "levelbanner_leaderboard",
        "us": "Leaderboard",
        "nl": "Scorebord",
        "de": "Bestenliste",
        "es": "Posiciones",
        "pt": "Posições",
        "cz": "Žebříček",
        "fr": "Meilleurs scores",
        "it": "Posizioni",
        "jr": "Most Wanted Pirates",
        "jp": "スコアボード",
        "ru": "Таблица лидеров"
    },
    {
        "textId": "levelbanner_loading",
        "us": "Loading...",
        "nl": "Laden...",
        "de": "Laden...",
        "es": "Cargando",
        "pt": "Carregar",
        "cz": "Načítání",
        "fr": "Chargement",
        "it": "Ricarica",
        "jr": "Sailin' to the destination",
        "jp": "ローディング",
        "ru": "Загрузка..."
    },
    {
        "textId": "levelbanner_time",
        "us": "Time",
        "nl": "Tijd",
        "de": "Zeit",
        "es": "Tiempo",
        "pt": "Tempo",
        "cz": "Čas",
        "fr": "Temps",
        "it": "Tempo",
        "jr": "Knots",
        "jp": "時間",
        "ru": "Время"
    },
    {
        "textId": "levelbanner_published",
        "us": "Published",
        "nl": "Gepubliceerd",
        "de": "Veröffentlicht",
        "es": "Publicado",
        "pt": "Publicados",
        "cz": "Zveřejněno",
        "fr": "Publié",
        "it": "Pubblicato",
        "jr": "Discovered",
        "jp": "発売時期",
        "ru": "Опубликовано"
    },
    {
        "textId": "levelbanner_updated",
        "us": "Updated",
        "nl": "Geupdate",
        "de": "Aktualisiert",
        "es": "Actualizado",
        "pt": "Atualizada",
        "cz": "Aktualizováno",
        "fr": "Mise à jour",
        "it": "Aggiornato",
        "jr": "Revisited",
        "jp": "最終更新日",
        "ru": "Обновлено"
    },
    {
        "textId": "levelbanner_noentries",
        "us": "No entries",
        "nl": "Geen scores",
        "de": "Keine Einträge",
        "es": "No Hay Entradas",
        "pt": "Vazio",
        "cz": "Žádné záznamy",
        "fr": "Aucun score",
        "it": "Non c'è nulla",
        "jr": "Treasure unclaimed",
        "jp": "スコアなし",
        "ru": "Нет посищений"
    },
    {
        "textId": "levelbanner_select",
        "us": "Select",
        "nl": "Selecteer",
        "de": "Auswählen",
        "es": "Seleccione",
        "pt": "Selecione",
        "cz": "Vybrat",
        "fr": "Sélectionner",
        "it": "Selezionare",
        "jr": "Pick",
        "jp": "選択",
        "ru": "Выбирать"
    },
    {
        "textId": "userpage_levelspublished",
        "us": "Levels Published",
        "nl": "Levels Gepubliceerd",
        "de": "Level veröffentlicht",
        "es": "Niveles publicados",
        "pt": "Níveis publicados",
        "cz": "Zveřejněné levely",
        "fr": "Niveaux publiés",
        "it": "Livelli pubblicati",
        "jr": "Islands Mapped",
        "jp": "作成されたレベル",
        "ru": "Опубликовано"
    },
    {
        "textId": "userpage_averagerating",
        "us": "Average Rating",
        "nl": "Gemiddelde beoordeling",
        "de": "Durchschnittliche Bewertung",
        "es": "Puntuacion Average",
        "pt": "Pontuação média",
        "cz": "Průměrné hodnocení",
        "fr": "Score moyen",
        "it": "Punteggio medio",
        "jr": "Reputation",
        "jp": "レベルの平均品質",
        "ru": "Средний рейтинг"
    },
    {
        "textId": "userpage_levelsfeatured",
        "us": "Levels Featured",
        "nl": "Levels Aanbevolen",
        "de": "Empfohlene Level",
        "es": "Niveles presentados",
        "pt": "Níveis apresentados",
        "cz": "Doporučené levely",
        "fr": "Niveaux en vedette",
        "it": "Livelli presenti",
        "jr": "Scurvy Approved Islands",
        "jp": "スペシャル・レベル",
        "ru": "Уровни показаны"
    },
    {
        "textId": "userpage_totalgameplays",
        "us": "Total Gameplays",
        "nl": "Totaal gespeeld",
        "de": "Gesamte Spieleranzahl",
        "es": "Total de jugadas",
        "pt": "Total De Jogadas",
        "cz": "Hráno celkem",
        "fr": "Total des jeux",
        "it": "Riproduzioni totali",
        "jr": "Total Voyages",
        "jp": "総プレイ数",
        "ru": "Геймплеи за всё время"
    },
    {
        "textId": "userpage_levels",
        "us": "Levels",
        "nl": "Levels",
        "de": "Levels",
        "es": "Nivel",
        "pt": "Níveis",
        "cz": "Levely",
        "fr": "Niveaux",
        "it": "Livelli",
        "jr": "Islands",
        "jp": "レベル",
        "ru": "Уровни"
    },
    {
        "textId": "userpage_favorites",
        "us": "Favorites",
        "nl": "Favorieten",
        "de": "Favoriten",
        "es": "Favoritos",
        "pt": "Favoritos",
        "cz": "Oblíbené",
        "fr": "Favoris",
        "it": "Preferiti",
        "jr": "Treasured",
        "jp": "お気に入りレベル",
        "ru": "Фавориты"
    },
    {
        "textId": "userpage_membersince",
        "us": "Member since",
        "nl": "Lid sinds",
        "de": "Spieler seit",
        "es": "Miembro desde",
        "pt": "Membro desde",
        "cz": "Členem od",
        "fr": "Membre depuis",
        "it": "Membro da",
        "jr": "Set sea on",
        "jp": "JollyWorldに参加した日",
        "ru": "Присоеденился в"
    },
    {
        "textId": "share_sharing",
        "us": "Sharing",
        "nl": "Delen",
        "de": "Teilen",
        "es": "Compartir",
        "pt": "Compartilhar",
        "cz": "Sdílení",
        "fr": "Partager",
        "it": "Condividere",
        "jr": "Share with yer mates.",
        "jp": "シェアリング",
        "ru": "Поделиться игрой"
    },
    {
        "textId": "share_levellink",
        "us": "Level link",
        "nl": "Level link",
        "de": "Level link",
        "es": "Enlace",
        "pt": "Link",
        "cz": "Odkaz",
        "fr": "Relier",
        "it": "Link",
        "jr": "Island coordinates",
        "jp": "レベルへのリンク",
        "ru": "Ссылка уровня"
    },
    {
        "textId": "share_shareby",
        "us": "Or share by",
        "nl": "Of deel met",
        "de": "Oder teilen mit",
        "es": "Compartido por",
        "pt": "Compartilhado por",
        "cz": "Nebo sdílet s",
        "fr": "Partagé par",
        "it": "Condiviso da",
        "jr": "Alternate routes",
        "jp": "ソーシャルメディアで共有する",
        "ru": "Или поделиться"
    },
    {
        "textId": "discord_getinvolved",
        "us": "Get Involved!",
        "nl": "Doe Mee!",
        "de": "Mach mit!",
        "es": "¡Involucrarse!",
        "pt": "Envolver-se!",
        "cz": "Přidej se!",
        "fr": "Être impliqué!",
        "it": "Mettersi in gioco!",
        "jr": "Join the tavern",
        "jp": "私たちの活動に参加してください",
        "ru": "Станьте частью нашего дискорд сервера"
    },
    {
        "textId": "discord_content",
        "us": "Meet level creators, chat with fellow Jolly players, drop suggestions for the game, report bugs, share your creations or learn new tips on how to beat certain levels. This is also the place where new big updates will be announced first!",
        "nl": "Ontmoet level ontwikkelaars, praat met andere Jolly spelers, drop suggesties for het spel, rapporteer bugs, deel jou creaties of leer nieuwe trucs om levels makkelijker te verslaan. Dit is ook de plek waar nieuwe grote updates als eerst worden aangekondigd!",
        "de": "Treffe Level Autoren, chatte mit anderen Spielern, melde Bugs, teile deine Kreationen oder lerne Tips um bestimmte Level zu bestehen. Neue Updates werden hier zuerst angekündigt!",
        "es": "Conozca a los creadores de nivel, chatee con otros jugadores alegre, elimine sugerencias para el juego, informe a los errores, comparta sus creaciones o aprende nuevos consejos sobre cómo superar ciertos niveles. ¡Este es también el lugar donde primero se anunciarán las nuevas grandes actualizaciones!",
        "pt": "Conheça os criadores de nível, converse com outros jogadores da Jolly, solte sugestões para o jogo, relate insetos, compartilhe suas criações ou aprenda novas dicas sobre como superar determinados níveis. Este também é o lugar onde novas grandes atualizações serão anunciadas primeiro!",
        "cz": "Seznamte se s tvůrci levelů, chatujte s ostatními hráči, zanechte nám své návrhy na hru, hlaste chyby, sdílejte své výtvory nebo se naučte nové triky, jak pokořit určité úrovně. O nových aktualizacích se zde dozvíte jako první!",
        "fr": "Rencontrez des créateurs de niveau, discutez avec ses collègues joueurs Jolly, déposez des suggestions pour le jeu, signalez des bugs, partagez vos créations ou apprenez de nouveaux conseils sur la façon de battre certains niveaux. C'est aussi l'endroit où de nouvelles grandes mises à jour seront annoncées en premier!",
        "it": "Incontra i creatori di livelli, chatta con altri jolly giocatori, drop suggerimenti per il gioco, segnala bug, condividi le tue creazioni o impara nuovi suggerimenti su come battere determinati livelli. Questo è anche il luogo in cui verranno annunciati nuovi grandi aggiornamenti!",
        "jr": "Hang out with yer mates and fellow ship-builders, drop suggestions for the game, fix yer ship, share your creations or learn new tips on how to beat certain levels. This also be the place where new big updates will be announced first! (NOT FINISHED)",
        "jp": "レベルクリエイターとの出会い、JollyWorldの仲間とのチャット、ゲームへの提案、バグの報告、自分の作品の共有、あるレベルの倒し方の新しいヒントを学ぶことができます。また、ここは新しい大型アップデートが最初に発表される場所でもあります。",
        "ru": "Знакомтесь с создателями уровней, общайтесь с другими игроками, предлогайте идеи для уровней, сообщайте об ошибках, делитесь своими творениями или узнайте новые советы о том, как пройти определенные уровни. Тут также будут анонсированы новые большие обновления!"
    },
    {
        "textId": "levelgui_pause",
        "us": "Pause",
        "nl": "Pauze",
        "de": "Pause",
        "es": "Pausar",
        "pt": "Pausar",
        "cz": "Pauza",
        "fr": "Pause",
        "it": "Pausa",
        "jr": "Stop the ship",
        "jp": "あいだをおく",
        "ru": "Пауза"
    },
    {
        "textId": "levelgui_resume",
        "us": "Resume",
        "nl": "Hervat",
        "de": "Zurück",
        "es": "Resumir",
        "pt": "Continuar",
        "cz": "Pokračovat",
        "fr": "Continuer",
        "it": "Ricapitolare",
        "jr": "Continue fightin'",
        "jp": "レジュメ",
        "ru": "Продолжить"
    },
    {
        "textId": "levelgui_reset",
        "us": "Reset",
        "nl": "Reset",
        "de": "Zurücksetzen",
        "es": "Resetear",
        "pt": "Resetar",
        "cz": "Restartovat",
        "fr": "Reset",
        "it": "Resettare",
        "jr": "Start the raid all over",
        "jp": "リセット",
        "ru": "Перезагрузить"
    },
    {
        "textId": "levelgui_retry",
        "us": "Retry",
        "nl": "Opnieuw",
        "de": "Neustart",
        "es": "Intentar De Nuevo",
        "pt": "Tentar novamente",
        "cz": "Opakovat",
        "fr": "Recommencer",
        "it": "Riprova",
        "jr": "Pick up where ye last left off",
        "jp": "再試行",
        "ru": "Повторить"
    },
    {
        "textId": "levelgui_exittest",
        "us": "Exit Test",
        "nl": "Sluit Test",
        "de": "Test Verlassen",
        "es": "Salir Del Test",
        "pt": "Sar do teste",
        "cz": "Opustit test",
        "fr": "Quitter le test",
        "it": "Esci dal test",
        "jr": "Swim back to shore",
        "jp": "テストモードの終了",
        "ru": "Выйти из испытания"
    },
    {
        "textId": "levelgui_youlose",
        "us": "You lose!",
        "nl": "Verliezer!",
        "de": "Du hast verloren!",
        "es": "Perdiste",
        "pt": "Você perdeu!",
        "cz": "Prohrál jsi",
        "fr": "Tu as perdu !",
        "it": "Hai perso",
        "jr": "Yer with Davy Jones!",
        "jp": "お前の負けだ！",
        "ru": "Вы проиграли!"
    },
    {
        "textId": "levelgui_youwin",
        "us": "You win!",
        "nl": "Winnaar!",
        "de": "Du hast gewonnen!",
        "es": "Ganaste",
        "pt": "Você ganhou!",
        "cz": "Vyhrál jsi",
        "fr": "Tu as gagné !",
        "it": "Ha vinto",
        "jr": "Ye found the treasure!",
        "jp": "私のホバークラフトはウナギでいっぱいです",
        "ru": "Вы победили!"
    },
    {
        "textId": "tutorial_skip_button",
        "us": "Skip",
        "nl": "Overslaan",
        "de": "Überspringen",
        "es": "Saltear",
        "pt": "Pular",
        "cz": "Přeskočit",
        "fr": "Sauter",
        "it": "Saltare",
        "jr": "Nah",
        "jp": "スキップ",
        "ru": "Прорустить"
    },
    {
        "textId": "editorheader_exit",
        "us": "Exit",
        "nl": "Verlaat",
        "de": "Verlassen",
        "es": "Salir",
        "pt": "Sair",
        "cz": "Odejít",
        "fr": "Quitter",
        "it": "Partire",
        "jr": "Abandon",
        "jp": "でぐち",
        "ru": "Выйти"
    },
    {
        "textId": "editorheader_logout",
        "us": "LOGOUT",
        "nl": "UITLOGGEN",
        "de": "AUSLOGGEN",
        "es": "Salir",
        "pt": "Deslogar",
        "cz": "Odhlásit se",
        "fr": "Se déconnecter",
        "it": "Partire",
        "jr": "DROP ANCHOR",
        "jp": "ログアウト",
        "ru": "ВЫЙТИ"
    },
    {
        "textId": "multiplayer_vote",
        "us": "Vote",
        "nl": "Stem",
        "de": "Abstimmung",
        "es": "Votar",
        "pt": "Voto",
        "cz": "Hlasování",
        "fr": "Vote",
        "it": "Votazione",
        "jr": "Vote",
        "jp": "投票",
        "ru": "Проголосовать"
    },
    {
        "textId": "multiplayer_replay",
        "us": "Replay",
        "nl": "Opnieuw",
        "de": "Wiederholung",
        "es": "Repetición",
        "pt": "Replay",
        "cz": "Přehrát",
        "fr": "Rejouer",
        "it": "Rigiocare",
        "jr": "Plunder again",
        "jp": "リプレイ",
        "ru": "Воспроизвести"
    },
    {
        "textId": "multiplayer_gamefinished_client",
        "us": "Game finished, vote for next level",
        "nl": "Game beëindigd, stem voor het volgende level",
        "de": "Spiel beendet, stimmen Sie für das nächste Level ab",
        "es": "Juego terminado, vote por el siguiente nivel",
        "pt": "Jogo terminado, vote no próximo nível",
        "cz": "Hra skončila, hlasujte pro další úroveň",
        "fr": "Jeu terminé, votez pour le niveau suivant",
        "it": "Il gioco è finito, vota per il livello successivo",
        "jr": "Voyage over, let the Captain know where ye want to go",
        "jp": "ゲーム終了、次のレベルへの投票",
        "ru": "Игра закончена, проголосуйте за следующий уровень"
    },
    {
        "textId": "multiplayer_gamefinished_admin",
        "us": "Game finished, pick the next level",
        "nl": "Game beëindigd, kies het volgende level",
        "de": "Spiel beendet, die nächste Level auswählen",
        "es": "Juego terminado, elige el siguiente nivel",
        "pt": "Jogo terminado, escolha o próximo nível",
        "cz": "Hra skončila, vyberte další úroveň",
        "fr": "Jeu terminé, choisissez le niveau suivant",
        "it": "Gioco finito, scegli il livello successivo",
        "jr": "Voyage over, start the next one",
        "jp": "ゲーム終了、次のレベルを選択",
        "ru": "Игра закончена, выберите следующий уровень"
    },
    {
        "textId": "multiplayer_gameendssoon",
        "us": "Players finished, game is ending soon..",
        "nl": "Spelers zijn gefinished, game zal snel eindigen..",
        "de": "Die Spieler beenden, das Spiel endet bald.",
        "es": "Los jugadores terminaron, el juego termina pronto.",
        "pt": "Os jogadores terminaram, o jogo está terminando em breve ..",
        "cz": "Hráči skončili, hra skončí brzy ..",
        "fr": "Les joueurs terminés, le jeu se termine bientôt.",
        "it": "I giocatori finiti, il gioco finisce presto ..",
        "jr": "Yer crew's bored, endin' soon.",
        "jp": "プレイヤーは終了、ゲームはまもなく終了",
        "ru": "Игроки закончили, игра скоро заканчивается .."
    },
    {
        "textId": "multiplayer_countdown",
        "us": "Game ends in %%s",
        "nl": "Game eindigt in %%s",
        "de": "Das Spiel endet in %% s",
        "es": "El juego termina en %% S",
        "pt": "O jogo termina em %% s",
        "cz": "Hra končí v %% s",
        "fr": "Le jeu se termine par %% S",
        "it": "Il gioco termina in %% s",
        "jp": "でゲーム終了 %%s",
        "ru": "Игра заканчивается в %% сек"
    },
    {
        "textId": "multiplayer_switchcamera",
        "us": "Switch Camera",
        "nl": "Wissel Camera",
        "de": "Kamera wechseln",
        "es": "Cámara de cambio",
        "pt": "Câmera de troca",
        "cz": "Přepněte kameru",
        "fr": "Commutation de la caméra",
        "it": "Switch Camera",
        "jp": "スイッチカメラ",
        "ru": "Переключить камеру"
    },
    {
        "textId": "multiplayer_waitingforothers",
        "us": "Waiting for other players to finish",
        "nl": "Wachten tot andere spelers klaar zijn",
        "de": "Warten darauf, dass andere Spieler fertig sind",
        "es": "Esperando que otros jugadores terminen",
        "pt": "Esperando que outros jogadores terminem",
        "cz": "Čekání na dokončení ostatních hráčů",
        "fr": "En attendant que les autres joueurs finissent",
        "it": "Aspettando che altri giocatori finiscano",
        "jr": "Waitin' for other maties to catch up",
        "jp": "他のプレイヤーのプレイ終了を待つ",
        "ru": "Ждем пока другие игроки закончат"
    },
    {
        "textId": "multiplayer_startingin",
        "us": "Starting in %%..",
        "nl": "Beginnend in %% ..",
        "de": "Beginnend in %% ..",
        "es": "Comenzando en %% ..",
        "pt": "Começando em %% ..",
        "cz": "Počínaje %% ..",
        "fr": "Commencer en %% ..",
        "it": "A partire da %% ..",
        "jr": "Plunderin' in %% ..",
        "jp": "でゲーム開始予定 %%",
        "ru": "Начинаем в %% .."
    },
    {
        "textId": "multiplayer_voted",
        "us": "Voted",
        "nl": "Gestemd",
        "de": "Gewählt",
        "es": "Votado",
        "pt": "Votado",
        "cz": "Hlasoval",
        "fr": "Voté",
        "it": "Votato",
        "jp": "投票済み",
        "ru": "Проголосовал"
    },
    {
        "textId": "multiplayer_go",
        "us": "GO!!!",
        "nl": "GAAN!!!",
        "de": "GEHEN!!!",
        "es": "¡¡¡VAMOS!!!",
        "pt": "VAI!!!",
        "cz": "JÍT!!!",
        "fr": "ALLER!!!",
        "it": "ANDARE!!!",
        "jr": "LAND HO!",
        "jp": "ゴー!!!",
        "ru": "ВПЕРЁД!!!"
    },
    {
        "textId": "multiplayer_waitingplayers",
        "us": "Waiting for other players %% / **",
        "nl": "Op andere spelers wachten %% / **",
        "de": "Warten auf andere Spieler %% / **",
        "es": "Esperando a otros jugadores %% / **",
        "pt": "Esperando por outros jogadores %% / **",
        "cz": "Čekání na další hráče %% / **",
        "fr": "En attente d'autres joueurs %% / **",
        "it": "Aspettando altri giocatori %% / **",
        "jp": "他のプレイヤーを待っている %% / **",
        "ru": "В ожидании других игроков %% / **"
    },
    {
        "textId": "multiplayer_returntolobby",
        "us": "Return to Lobby",
        "nl": "Keer terug naar de lobby",
        "de": "Kehren Sie zur Lobby zurück",
        "es": "Regresar al lobby",
        "pt": "Voltar ao lobby",
        "cz": "Návrat do lobby",
        "fr": "Retour au hall",
        "it": "Torna alla lobby",
        "jr": "Return to port",
        "jp": "ロビーに戻る",
        "ru": "Вернуться в лобби"
    },
    {
        "textId": "multiplayer_tochat",
        "us": "To chat click here or press 'Enter' key",
        "nl": "Voor chatten klik hier of druk 'Enter' toets",
        "es": "Para chatear click aqui o presiona enter",
        "pt": "Para Chat clique aqui ou pressione enter",
        "fr": "Pour Chat, cliquez ici ou appuyez sur Entrée",
        "it": "Per chattare clicca qui o premi invio",
        "jr": "To talk, click here or press the Enter key",
        "jp": "チャットするにはここをクリックするか、'Enter'キーを押してください。",
        "ru": "Для чата нажмите здесь или нажмите клавишу «Enter»"
    },
    {
        "textId": "multiplayer_invitelink",
        "us": "Invite link",
        "nl": "Uitnodigings link",
        "de": "Einladungslink",
        "es": "Enlace de invitación",
        "pt": "Link para convite",
        "cz": "Odkaz na pozvání",
        "fr": "Lien d'invitation",
        "it": "Link di invito",
        "jr": "X marks the spot",
        "jp": "招待コード",
        "ru": "Пригл. игрока ссылкой"
    },
    {
        "textId": "multiplayer_copied",
        "us": "copied",
        "nl": "gekopieerd",
        "de": "kopiert",
        "es": "copiado",
        "pt": "copiado",
        "cz": "zkopírováno",
        "fr": "copié",
        "it": "copiato",
        "jp": "コピー",
        "ru": "Скопировано"
    }
]
init();
