export var LoadCoreAssets = function (loader){
    loader.add("assets/images/bodyparts.json")
        .add("assets/images/vehicles.json")
        .add("assets/images/Characters1.json")
        .add("assets/images/Vehicles1.json")
        .add("assets/images/Decals.json")
        .add("assets/images/TextureTiles.json")
        .add("assets/images/textures/tile1.jpg")
        .add("assets/images/textures/tile2.jpg")
        .add("assets/images/textures/tile3.jpg")
        .add("assets/images/textures/tile4.jpg")
        .add("assets/images/textures/tile5.jpg")
        .add("assets/images/textures/tile6.jpg")
        .add("assets/images/textures/tile7.jpg")
        .add("assets/images/textures/tile8.jpg")
        .add("assets/images/textures/tile9.jpg")
        .add("assets/images/textures/tile10.jpg")
        .add("assets/images/textures/tile11.jpg")
        .add("assets/images/textures/tile12.jpg")
        .add("assets/images/textures/tile13.jpg")
        .add("assets/images/textures/tile14.jpg")
        .add("assets/images/textures/tile15.jpg")
        .add("assets/images/textures/tile16.jpg")
        .add("assets/images/textures/tile17.jpg")
        .add("worldData", "data/worldData.json")
        .add("vehicleData", "data/vehicle.json")
        .add("characterData", "data/character.json")
        .add("characterData1", "data/character1.json");
}