export var LoadCoreAssets = function (loader){
    loader.add("Characters_1.json", "assets/images/characters/Characters_1.json")
        .add("RickAndMorty.json", "assets/images/characters/RickAndMorty.json")
        .add("Characters_Gore.json", "assets/images/characters/Characters_Gore.json")
        .add("Vehicles_1.json", "assets/images/vehicles/Vehicles_1.json")
        .add("assets/images/particles/Decals.json")
        .add("Movement.json", "assets/images/prefabs/Movement.json")
        .add("Construction.json", "assets/images/prefabs/Construction.json")
        .add("Nature.json", "assets/images/prefabs/Nature.json")
        .add("Weapons.json", "assets/images/prefabs/Weapons.json")
        .add("Level.json", "assets/images/prefabs/Level.json")
        /*TILE DATA*/
        .add("Dirt.jpg", "assets/images/textures/Dirt.jpg")
        .add("Grass.jpg", "assets/images/textures/Grass.jpg")
        .add("Fence.png", "assets/images/textures/Fence.png")
        .add("YellowCat.jpg", "assets/images/textures/YellowCat.jpg")
        .add("RedWhiteBlock.jpg", "assets/images/textures/RedWhiteBlock.jpg")
        .add("PixelatedWater.jpg", "assets/images/textures/PixelatedWater.jpg")
        .add("PixelatedStone.jpg", "assets/images/textures/PixelatedStone.jpg")
        .add("PixelatedDirt.jpg", "assets/images/textures/PixelatedDirt.jpg")
        .add("PixelatedGrass.jpg", "assets/images/textures/PixelatedGrass.jpg")
        .add("GoldenBlock.jpg", "assets/images/textures/GoldenBlock.jpg")
        .add("Brick0.jpg", "assets/images/textures/Brick0.jpg")
        .add("Brick1.jpg", "assets/images/textures/Brick1.jpg")
        .add("Brick2.jpg", "assets/images/textures/Brick2.jpg")
        .add("WhiteBlock.jpg", "assets/images/textures/WhiteBlock.jpg")
        /*PARTICLE DATA*/
        .add("blood-particles-data", "data/emitter_blood.json")
        .add("particle.png", "assets/images/particles/particle.png")
        .add("particle-grey.png", "assets/images/particles/particle-grey.png")
        .add("gore-cloud.png", "assets/images/particles/gore-cloud.png")
        /*WORLD DATA*/
        .add("worldData", "data/worldData.json")
        .add("characterData1", "data/character1.json")
        .add("testData", "data/testData.json")
        .add("testData2", "data/testData2.json");
}