export var LoadCoreAssets = function (loader){
    loader.add("bodyparts.json", "assets/images/bodyparts.json")
        .add("vehicles.json", "assets/images/vehicles.json")
        .add("Characters1.json", "assets/images/Characters1.json")
        .add("Vehicles1.json", "assets/images/Vehicles1.json")
        .add("assets/images/Decals.json")
        .add("Movement.json", "assets/images/prefabs/Movement.json")
        /*TILE DATA*/
        .add("tile1.jpg", "assets/images/textures/tile1.jpg")
        .add("tile2.jpg", "assets/images/textures/tile2.jpg")
        .add("tile3.jpg", "assets/images/textures/tile3.jpg")
        .add("tile4.jpg", "assets/images/textures/tile4.jpg")
        .add("tile5.jpg", "assets/images/textures/tile5.jpg")
        .add("tile6.jpg", "assets/images/textures/tile6.jpg")
        .add("tile7.jpg", "assets/images/textures/tile7.jpg")
        .add("tile8.jpg", "assets/images/textures/tile8.jpg")
        .add("tile9.jpg", "assets/images/textures/tile9.jpg")
        .add("tile10.jpg", "assets/images/textures/tile10.jpg")
        .add("tile11.jpg", "assets/images/textures/tile11.jpg")
        .add("tile12.jpg", "assets/images/textures/tile12.jpg")
        .add("tile13.jpg", "assets/images/textures/tile13.jpg")
        .add("tile14.jpg", "assets/images/textures/tile14.jpg")
        .add("tile15.jpg", "assets/images/textures/tile15.jpg")
        .add("tile16.jpg", "assets/images/textures/tile16.jpg")
        .add("tile17.jpg", "assets/images/textures/tile17.jpg")
        /*PARTICLE DATA*/
        .add("blood-particles-data", "data/emitter_blood.json")
        .add("particle.png", "assets/images/particles/particle.png")
        .add("particle-grey.png", "assets/images/particles/particle-grey.png")
        /*WORLD DATA*/
        .add("worldData", "data/worldData.json")
        .add("vehicleData", "data/vehicle.json")
        .add("characterData", "data/character.json")
        .add("characterData1", "data/character1.json")
        .add("testData", "data/testData.json");
}