import 'FireBaseManager.js'
import 'AssetList.js'
import 'UIManager.js'
import 'Vehicle.js'
import 'Game-gui.js'
import 'PrefabData.js'
import 'B2dEditor.js'
import 'Settings.js'
import '../libs/pixi-spine.js'
import '../libs/pixi-heaven.js'
import 'Game.js'

import '../libs/semantic/dist/semantic.css'
import 'css/B2dEditor.css'
import 'css/dat-gui-light-theme.css'